# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-08 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postal_code', models.CharField(max_length=8)),
                ('place_name', models.CharField(max_length=50)),
                ('admin_name1', models.CharField(max_length=50)),
                ('admin_code1', models.CharField(max_length=3)),
                ('admin_name2', models.CharField(max_length=50)),
                ('admin_code2', models.IntegerField()),
                ('latitude', models.IntegerField()),
                ('longitude', models.IntegerField()),
            ],
        ),
    ]
