# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-11 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climate_map', '0001_squashed_0005_auto_20160209_2031'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_id', models.IntegerField()),
                ('id_code', models.CharField(max_length=11)),
                ('latitude', models.DecimalField(decimal_places=4, max_digits=8)),
                ('longitude', models.DecimalField(decimal_places=4, max_digits=8)),
                ('station_state', models.CharField(max_length=2)),
                ('station_name', models.CharField(max_length=30)),
            ],
        ),
    ]
