# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-11 06:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('climate_map', '0002_station'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='index_id',
        ),
    ]
